# Install libraries
install.packages("randomForest")
install.packages("gbm")
install.packages("neuralnet")
install.packages("MVN")
install.packages("forecast")
install.packages("tseries")
install.packages("ggplot2")
install.packages("ggfortify")
install.packages("ggpubr")
install.packages("fpp2")
install.packages("fpp3")
install.packages("forecastHybrid")
install.packages("forecastML")
install.packages("forecastMLExtra")
install.packages("forecastMLData")
install.packages("forecastMLPlots")
install.packages("forecastMLUtils")

# Import libraries
library(randomForest)
library(gbm)
library(neuralnet)
library(MVN)
library(GGally)
library(forecast)
library(tseries)
library(ggplot2)
library(ggfortify)
library(ggpubr)
library(fpp2)
library(fpp3)
